### ISSUE TITLE
Habit tracker

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [MonalikaPatnaik/UMatter#68] opened 2023-05-20 10:59 UTC
Develop an interactive habit tracker that allow users to input their bad habits and track their progress over time. It can provide visual representation  such as chart, graphs to help users see there progress and stay motivated.

kindly assign me to solve this issue as GSoC'23 Contributor.

**Comment by MonalikaPatnaik** [comment] 2023-05-20 11:59
@Suchitra-Sahoo you are assigned..
Thanks!

**Comment by Suchitra-Sahoo** [comment] 2023-05-25 16:47
> Heyy @Suchitra-Sahoo are you working on this?

Yes....I'm working on it. My exams were going on so couldn't work fast.

**Comment by MonalikaPatnaik** [comment] 2023-05-25 18:03
Okok..take your time and good luck with your exams!

**Comment by vk20july** [comment] 2023-06-06 16:40
I want to work on this issue under gssoc'23

**Comment by MonalikaPatnaik** [comment] 2023-06-07 08:12
@vk20july let me know if u can't!

**Comment by vk20july** [comment] 2023-06-07 08:17
> @vk20july let me know if u can't!

yes mam i will do but i need some time to figure out

**Comment by MonalikaPatnaik** [comment] 2023-06-07 08:25
Umm it's already been late...take ur time to figure out and if u can't just lmk..will assign some other issue to u !

**Comment by vk20july** [comment] 2023-06-07 08:38
> Umm it's already been late...take ur time to figure out and if u can't just lmk..will assign some other issue to u !

ok mam I will let you know if any problem occur
let me take some 4-5 days mam

**Comment by ManavMalhotra** [comment] 2023-06-22 14:12
Hi, I have already worked on this particular issue and would like to work on this. If the issue is still open, I kindly request to be assigned to me under GSSOC'23.

**Closed** 2023-06-25 07:13 UTC
Labels: enhancement, gssoc23, Assigned
