### ISSUE TITLE
Updating the UI of buttons in Website to make it look more good

### ISSUE THREAD

**Issue by ojasaklechayt** [MonalikaPatnaik/UMatter#402] opened 2023-05-26 12:40 UTC
**Feature idea.**

1. Improvement in button color pallet
2. Added border into mode changing button

**Describe the solution you'd like**

1. Button Color Pallet

Before:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/90605717/765d7626-b0be-484c-8f87-f14052b64acc)

After: 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/90605717/bdf63b2d-e81a-4256-84c0-453671c79a83)

3. Mode Changing Button

Before:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/90605717/6e8f7116-dcc8-4a39-823d-a9bb13671b30)

After:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/90605717/94cb582a-d332-4f89-a4db-f46849d0535e)

**Comment by prabhatsingh985** [comment] 2023-05-27 06:12
Can you please assign this issue to me , Can easily change this issue by writing a CSS

**Comment by ojasaklechayt** [comment] 2023-05-27 06:35
@MonalikaPatnaik made the pr

**Comment by MonalikaPatnaik** [comment] 2023-05-27 07:13
Hey pls don't make a PR until the issue is not been assigned to you!
Check my comment in your PR!

**Comment by MonalikaPatnaik** [comment] 2023-05-27 07:24
Hey..you can work on improving the UI of buttons!
Thanks!

**Comment by prabhatsingh985** [comment] 2023-05-27 09:33
@MonalikaPatnaik Okay great

**Closed** 2023-05-28 08:43 UTC
Labels: GSSOC'23, Assigned, Improve Design, Level2
