### ISSUE TITLE
[GSSOC'23] Toggling between dark and light mode correctly 

### ISSUE THREAD

**Issue by sharma21deepti** [MonalikaPatnaik/UMatter#306] opened 2023-05-23 20:49 UTC
When we switch for the light mode from dark mode only the color of navbar changes but footer still remains the same.

**Comment by MonalikaPatnaik** [comment] 2023-05-27 05:24
Heyy pls submit your PR soon otherwise will assign it to someone else!

**Comment by Shalini469717** [comment] 2023-05-28 00:52
Can I work on this?

**Comment by MonalikaPatnaik** [comment] 2023-05-28 03:16
Yes @Shalini469717 you can..
Submit your PR soon!

**Comment by Shalini469717** [comment] 2023-06-02 02:11
seems like the issue is fixed

**Closed** 2023-06-04 21:20 UTC
Labels: good first issue, gssoc23, Assigned
